default_platform(:ios)

platform :ios do
  desc "Build app for simulator"
  lane :build do
    sh("xcodebuild -project ./CryptoTrace.xcodeproj -scheme FinanceTracker -destination 'platform=iOS Simulator,name=iPhone 17 Pro Max' CODE_SIGNING_ALLOWED=NO build")
  end

  desc "Upload to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: "2RT7D98UVL",
      issuer_id: "c74868ac-5f2a-4fd3-a9c1-ac31caf36d30",
      key_filepath: "./fastlane/AuthKey_2RT7D98UVL.p8"
    )

    increment_build_number(
      build_number: Time.now.to_i,
      xcodeproj: "./CryptoTrace.xcodeproj"
    )

    build_app(
      project: "./CryptoTrace.xcodeproj",
      scheme: "FinanceTracker",
      export_method: "app-store",
      clean: true
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end
