name: iOS CI

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app

      - name: Build iOS App
        run: |
          xcodebuild \
            -project CryptoTrace.xcodeproj \
            -scheme FinanceTracker \
            -destination 'platform=iOS Simulator,name=iPhone 17 Pro Max' \
            CODE_SIGNING_ALLOWED=NO \
            build
